name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

permissions:
  contents: read

jobs:
  create-tag:
    permissions:
      contents: write  # for creating git tags
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Create Tag
        uses: jbw976/create-tag@6acde0c99312d603f94cae2309a1589a0b5c36cc # allow-path-prefix
        with:
          version: ${{ github.event.inputs.version }}
          message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create apis/ Tag
        uses: jbw976/create-tag@6acde0c99312d603f94cae2309a1589a0b5c36cc # allow-path-prefix
        with:
          version: apis/${{ github.event.inputs.version }}
          message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
